export * from "./AboutUs"
export { default as Home } from "./Home"
export { default as JoinUs } from "./JoinUs"
export { default as Login } from "./Login"
export * from "./RegisterRole"
export { default as RegisterUser } from "./RegisterUser"
export { default as RegisterPartner } from "./RegisterPartner"
export { default as ForgetEmail } from "./ForgetEmail"
export { default as UnregisteredBlogshopOwner } from "./UnregisteredBlogshopOwner"
export { default as PartnerAllProducts } from "./PartnerAllProducts"
export { default as ForgetPassword } from "./ForgetPassword"
export { default as InterestSurvey} from "./InterestSurvey"
export { default as PartnerProfile} from "./PartnerProfile"
export { default as AdminCategories} from "./AdminCategories"
export { default as AddProduct} from "./AddProduct"
export { default as UserHomepage} from "./UserHomepage"
export { default as UserCategories} from "./UserCategories"
export { default as UserProfile} from "./UserProfile"

export { default as Links} from "./Links"
